#!/bin/sh
# Auto-generated by agent-pm — rebuilds Flutter web on file changes.
# Uses mtime polling (every 2s) because inotify events do NOT propagate
# from macOS hosts into Linux containers via Docker Desktop's bind mount.
set -u

echo '[watch] flutter pub get…'
flutter pub get

echo '[watch] initial flutter build web --release (takes ~60-90s on cold cache)…'
flutter build web --release

echo '[watch] starting http.server on :8080…'
(cd build/web && python3 -m http.server 8080 --bind 0.0.0.0) &
SERVER_PID=$!
trap "kill $SERVER_PID 2>/dev/null; exit" INT TERM

echo '[watch] polling lib/ + pubspec.yaml every 2s for changes…'
touch /tmp/.last_build
while true; do
  CHANGED=$(find lib pubspec.yaml -newer /tmp/.last_build -type f 2>/dev/null | head -3)
  if [ -n "$CHANGED" ]; then
    touch /tmp/.last_build
    echo "[watch $(date +%H:%M:%S)] change detected: $(echo "$CHANGED" | tr '\n' ' ')"
    flutter build web --release && \
      echo "[watch $(date +%H:%M:%S)] rebuild done. Refresh browser."
  fi
  sleep 2
done
